// Generated by CoffeeScript 1.4.0
(function() {

  beforeEach(function() {
    return this.addMatchers({
      toBeNaN: function(nan) {
        return isNaN(nan);
      }
    });
  });

}).call(this);
